// TODO: User must verify these deadlines against Налоговый кодекс РК 2026.
// These are scaffolding defaults based on common knowledge of KZ tax deadlines.
// Rates and dates may have changed — always check the current legislation.

export interface DeadlineTemplate {
  tax_type: string;
  name: string;
  period: 'monthly' | 'quarterly' | 'half_year' | 'annual';
  due_day: number;
  due_month_offset: number; // months after period end
  description: string;
}

export const DEADLINES_BY_REGIME: Record<string, DeadlineTemplate[]> = {
  simplified_new: [
    {
      tax_type: 'simplified',
      name: 'Упрощённая декларация (910 форма)',
      period: 'half_year',
      due_day: 15,
      due_month_offset: 2,
      description: 'Форма 910.00 — полугодовая декларация по упрощённому режиму. 3% от дохода.',
    },
    {
      tax_type: 'ipn',
      name: 'ИПН с зарплаты (200 форма)',
      period: 'quarterly',
      due_day: 15,
      due_month_offset: 1,
      description: 'Декларация по ИПН и социальному налогу. Подаётся ежеквартально.',
    },
    {
      tax_type: 'opv',
      name: 'ОПВ (пенсионные взносы)',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Обязательные пенсионные взносы — 10% от дохода работника. Уплата — ежемесячно до 25 числа.',
    },
    {
      tax_type: 'so',
      name: 'СО (социальные отчисления)',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Социальные отчисления — 3.5% от дохода за вычетом ОПВ.',
    },
    {
      tax_type: 'osms',
      name: 'ОСМС (отчисления на медстрахование)',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Отчисления работодателя на ОСМС — 3% от дохода работника.',
    },
    {
      tax_type: 'vosms',
      name: 'ВОСМС (взносы на медстрахование)',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Взносы работника на ВОСМС — 2% от дохода.',
    },
  ],
  simplified_old: [
    {
      tax_type: 'simplified',
      name: 'Упрощённая декларация (910 форма)',
      period: 'half_year',
      due_day: 15,
      due_month_offset: 2,
      description: 'Форма 910.00 — полугодовая декларация.',
    },
    {
      tax_type: 'ipn',
      name: 'ИПН с зарплаты (200 форма)',
      period: 'quarterly',
      due_day: 15,
      due_month_offset: 1,
      description: 'Декларация по ИПН и СН.',
    },
    {
      tax_type: 'opv',
      name: 'ОПВ',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Обязательные пенсионные взносы.',
    },
    {
      tax_type: 'so',
      name: 'СО',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Социальные отчисления.',
    },
    {
      tax_type: 'osms',
      name: 'ОСМС',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Отчисления на ОСМС.',
    },
    {
      tax_type: 'vosms',
      name: 'ВОСМС',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Взносы на ВОСМС.',
    },
  ],
  general: [
    {
      tax_type: 'kpn',
      name: 'КПН (100 форма)',
      period: 'annual',
      due_day: 31,
      due_month_offset: 3,
      description: 'Декларация по корпоративному подоходному налогу — до 31 марта следующего года.',
    },
    {
      tax_type: 'kpn_advance',
      name: 'Авансовые платежи КПН',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Ежемесячные авансовые платежи по КПН.',
    },
    {
      tax_type: 'ipn',
      name: 'ИПН с зарплаты (200 форма)',
      period: 'quarterly',
      due_day: 15,
      due_month_offset: 1,
      description: 'Декларация по ИПН и СН.',
    },
    {
      tax_type: 'opv',
      name: 'ОПВ',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Обязательные пенсионные взносы.',
    },
    {
      tax_type: 'so',
      name: 'СО',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Социальные отчисления.',
    },
    {
      tax_type: 'osms',
      name: 'ОСМС',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Отчисления на ОСМС.',
    },
    {
      tax_type: 'vosms',
      name: 'ВОСМС',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Взносы на ВОСМС.',
    },
  ],
  retail_tax: [
    {
      tax_type: 'retail',
      name: 'Розничный налог (913 форма)',
      period: 'quarterly',
      due_day: 15,
      due_month_offset: 1,
      description: 'Декларация по розничному налогу — 3% от дохода.',
    },
    {
      tax_type: 'ipn',
      name: 'ИПН с зарплаты (200 форма)',
      period: 'quarterly',
      due_day: 15,
      due_month_offset: 1,
      description: 'Декларация по ИПН и СН.',
    },
    {
      tax_type: 'opv',
      name: 'ОПВ',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Обязательные пенсионные взносы.',
    },
    {
      tax_type: 'so',
      name: 'СО',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Социальные отчисления.',
    },
    {
      tax_type: 'osms',
      name: 'ОСМС',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Отчисления на ОСМС.',
    },
    {
      tax_type: 'vosms',
      name: 'ВОСМС',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Взносы на ВОСМС.',
    },
  ],
  patent: [
    {
      tax_type: 'patent',
      name: 'Патент (911 форма)',
      period: 'annual',
      due_day: 15,
      due_month_offset: 1,
      description: 'Расчёт стоимости патента — 1% от заявленного дохода.',
    },
    {
      tax_type: 'opv',
      name: 'ОПВ (за себя)',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Обязательные пенсионные взносы ИП за себя.',
    },
    {
      tax_type: 'so',
      name: 'СО (за себя)',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Социальные отчисления ИП за себя.',
    },
    {
      tax_type: 'osms',
      name: 'ОСМС (за себя)',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Отчисления на ОСМС ИП за себя.',
    },
    {
      tax_type: 'vosms',
      name: 'ВОСМС (за себя)',
      period: 'monthly',
      due_day: 25,
      due_month_offset: 0,
      description: 'Взносы на ВОСМС ИП за себя.',
    },
  ],
};
